services:
  filebrowser:
    container_name: filebrowser
    image: ghcr.io/gatzenga/filebrowser:latest
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./srv:/srv
      - ./config:/config
      - ./database:/database
